name = "cve-tips"
main = "src/index.ts"
compatibility_date = "2025-05-03"
account_id = "45b9b661255d3ed8530e11c41d9ba56b"

[[r2_buckets]]
binding = "R2"
bucket_name = "cve-tips"
preview_bucket_name = "cve-tips"
